version: '3.8'

services:
  myapp:
    image: ubuntu
    command: sleep infinity
    secrets:
      - my_secret
    environment:
      - MY_SECRET_FILE=/run/secrets/my_secret

secrets:
  my_secret:
    external: true