name: Convert PPTX to PDF

on:
  push:
    branches:
      - '**'
    paths:
      - 'ppt/**'  # Solo se ejecuta si hay cambios en "ppt/"

jobs:
  convert_pptx_to_pdf:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up LibreOffice
      run: sudo apt-get install -y libreoffice

    - name: Check for PPTX files
      run: |
        echo "Files to convert:"
        find . -name '*.pptx'

    - name: Convert PPTX to PDF
      run: |
        for pptx in $(find . -name '*.pptx'); do
          libreoffice --headless --convert-to pdf "$pptx"
        done
        mv *.pdf ./pdf

    - name: Commit PDF files
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add *.pdf
        git commit -m "Add converted PDFs"
        git push https://github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

