name: Convert PPTX to PDF

on:
  push:
    branches:
      - '**'

jobs:
  convert_pptx_to_pdf:
    runs-on: ubuntu-latest
    
    steps:
    # Paso 1: Configurar la versión de LibreOffice
    - name: Set up LibreOffice
      run: sudo apt-get install -y libreoffice

    # Paso 2: Comprobar los archivos .pptx
    - name: Check for PPTX files
      run: |
        echo "Files to convert:"
        find . -name '*.pptx'

    # Paso 3: Convertir archivos .pptx a .pdf
    - name: Convert PPTX to PDF
      run: |
        for pptx in $(find . -name '*.pptx'); do
          libreoffice --headless --convert-to pdf "$pptx"
        done

    # Paso 4: Subir los archivos PDF convertidos
    - name: Commit PDF files
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add *.pdf
        git commit -m "Add converted PDFs"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
